[package]
name = "decode_moi_ca"
version = "0.1.0"
edition = "2024"

[dependencies]
m4ri-rust = "0.4.0"
rug = "1.28.0"

[dependencies.vob]
version = "^2.0.6"
features = ["unsafe_internals", "serde"]
[dev-dependencies.serde_json]
version = "1.0"
